# Generated by Django 4.0.6 on 2022-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Основная надпись')),
                ('text', models.CharField(max_length=125, verbose_name='Дополнительная нажпись')),
                ('btn_p', models.CharField(max_length=15, verbose_name='Первая кнопка')),
                ('btn_w', models.CharField(max_length=15, verbose_name='Вторая кнопка')),
            ],
        ),
    ]
