# Generated by Django 4.0.6 on 2022-07-20 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intro',
            name='btn_p',
            field=models.CharField(max_length=20, verbose_name='Первая кнопка'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='btn_w',
            field=models.CharField(max_length=20, verbose_name='Вторая кнопка'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='text',
            field=models.CharField(max_length=140, verbose_name='Дополнительная нажпись'),
        ),
        migrations.AlterField(
            model_name='intro',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Основная надпись'),
        ),
    ]
