# Generated by Django 4.0.6 on 2022-07-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0002_alter_intro_btn_p_alter_intro_btn_w_alter_intro_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='We',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=30, verbose_name='Первая надпись')),
                ('text2', models.CharField(max_length=30, verbose_name='вторая надпись')),
                ('text3', models.CharField(max_length=30, verbose_name='Третья надпись')),
                ('text', models.CharField(max_length=30, verbose_name='Четвертая надпись')),
            ],
            options={
                'verbose_name': 'Почему мы',
                'verbose_name_plural': 'Почему мы',
            },
        ),
        migrations.AlterModelOptions(
            name='intro',
            options={'verbose_name': 'Первая секция', 'verbose_name_plural': 'Первая секция'},
        ),
    ]
