# Generated by Django 4.0.6 on 2022-07-20 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0003_we_alter_intro_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='we',
            old_name='text',
            new_name='text4',
        ),
    ]
