# Generated by Django 4.0.6 on 2022-07-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=40, verbose_name='Первая надпись')),
                ('text2', models.CharField(max_length=150, verbose_name='вторая надпись')),
                ('img', models.FileField(upload_to='img/main/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Проблемы',
                'verbose_name_plural': 'Проблемы',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Сервис', 'verbose_name_plural': 'Сервис'},
        ),
    ]
