# Generated by Django 4.0.6 on 2022-07-20 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0006_problems_alter_service_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Needs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=40, verbose_name='Первая надпись')),
                ('text2', models.CharField(max_length=60, verbose_name='вторая надпись')),
                ('btn_w', models.CharField(max_length=20, verbose_name='Кнопка')),
            ],
            options={
                'verbose_name': 'Не уверены?',
                'verbose_name_plural': 'Не уверены?',
            },
        ),
    ]
