# Generated by Django 4.0.6 on 2022-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0008_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.DecimalField(decimal_places=0, max_digits=1)),
                ('name', models.CharField(max_length=15, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Специализация',
                'verbose_name_plural': 'Специализация',
            },
        ),
    ]
