# Generated by Django 4.0.6 on 2022-07-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0010_alter_specializations_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='img/main/%Y/%m/%d/')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
