# Generated by Django 4.0.6 on 2022-07-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biipeco', '0011_talks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='img/main/%Y/%m/%d/')),
                ('name', models.CharField(max_length=20, verbose_name='Регион')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, verbose_name='Почта')),
                ('whatsapp', models.CharField(max_length=200, verbose_name='Whatsapp')),
                ('telegram', models.CharField(max_length=200, verbose_name='Telegram')),
                ('phone1', models.CharField(max_length=20, verbose_name='Телефон для страницы')),
                ('phone1_link', models.CharField(max_length=20, verbose_name='Телефон для ссылки (в формате +79000000000)')),
                ('phone2', models.CharField(max_length=20, verbose_name='Телефон')),
                ('phone2_link', models.CharField(max_length=20, verbose_name='Телефон для ссылки (в формате +79000000000)')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='talks',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
    ]
